name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: '3,17,35 8-18 * * *'

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "qiuwentao0823@gmail.com"
          git config --local user.name "ShermanQ"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "MakeUGreenAgain"
          git push
